server:
  port: 8084

spring:
  application:
    name: user-server
  
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    com.hanainplan.user: DEBUG
    org.springframework.web: DEBUG

# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

# CoolSMS 설정
coolsms:
  api-key: ${COOLSMS_API_HEY}
  api-secret: ${COOLSMS_API_SECRET}
  from-number: ${COOLSMS_FROM}
  test-number: "010-8965-0136"  # 실제 문자를 받을 하드코딩된 번호
